EXCLUDED_MATERIALS:
- COMMAND_BLOCK
- BARRIER
- STRUCTURE_VOID
- LIGHT
- CHAIN_COMMAND_BLOCK
- REPEATING_COMMAND_BLOCK
- STRUCTURE_BLOCK
- JIGSAW
- PETRIFIED_OAK_SLAB
- PLAYER_HEAD
- KNOWLEDGE_BOOK
- DEBUG_STICK
- BEDROCK
- REINFORCED_DEEPSLATE
- CHORUS_PLANT
- BUDDING_AMETHYST
- END_PORTAL_FRAME
- COMMAND_BLOCK_MINECART
- INFESTED_COBBLESTONE
- INFESTED_CHISELED_STONE_BRICKS
- INFESTED_STONE_BRICKS
- INFESTED_MOSSY_STONE_BRICKS
- INFESTED_CRACKED_STONE_BRICKS
- INFESTED_DEEPSLATE
- INFESTED_STONE

BLOCK_DROP_MAP: {}

DELETE_WORLDS_ON_RESTART: false