name: BlockRandomizer
version: '${project.version}'
main: me.sailex.blockrandomizer.BlockRandomizer
api-version: '1.20'
authors: [sailex]

commands:
  randomizer:
    permission: op
    usage: /<randomizer>